source 'http://rubygems.org'

gem 'rails', '3.1'

gem "sqlite3"
gem "mysql2"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.1.0"
  gem 'therubyracer'
  gem 'coffee-rails', "~> 3.1.0"
  gem 'coffee-filter'
  gem 'uglifier', '>= 1.0.3'
  gem 'haml'
  gem "compass", ">= 0.11.5"
end

gem 'jquery-rails'

# gem 'simple_form', '1.4.1'
# gem 'mini_magick', '3.3'
# gem 'carrierwave', '0.5.4'
# gem 'kaminari', '0.12.4'
# gem 'memcache-client', '1.8.5'
# gem 'colorize', '0.5.8'
gem 'zmq', "2.1.3"
gem 'json', '2.3.1'

gem 'activeadmin', "0.3"
gem 'meta_search',    '>= 1.1.0.pre'

gem "unicorn"

group :test, :development do
end
