source 'http://rubygems.org'

gem 'rails', '3.0.9'
gem "mysql2", "0.2.11"
gem "sqlite3", '~>1.3.0'
gem 'simple_form', '1.4.1'
gem 'mini_magick', '3.3'
gem 'carrierwave', '0.5.4'
gem 'jquery-rails', '1.0.11'
gem 'kaminari', '0.12.4'
gem 'memcache-client', '1.8.5'
gem 'colorize', '0.5.8'
gem 'devise', '~>1.4.0'
gem 'zmq', "2.1.3"
gem 'json', '1.5.3'
gem "activeadmin", "0.2.2"

gem 'haml'
gem 'sass'

group :test, :development do
  gem "rspec"
  gem "rspec-rails"
  gem "factory_girl", "2.0.0.beta2"

  gem 'capybara'
  gem 'cucumber-rails'
  gem 'database_cleaner'

  gem 'mocha'
  gem 'spork'
end
