source 'http://rubygems.org'

gem 'rails', '3.0.9'
gem "mysql2", "0.2.11"
gem 'simple_form', '1.4.1'
gem 'mini_magick', '3.3'
gem 'carrierwave', '0.5.4'
gem 'resque', '1.17.1'
gem 'jquery-rails', '1.0.11'
gem 'whenever', '0.6.8', :require => false
gem 'kaminari', '0.12.4'
gem 'memcache-client', '1.8.5'
gem 'settingslogic', '2.0.6'
gem 'tagged-cache', '1.1.1'
gem 'colorize', '0.5.8'
gem 'devise', '1.4.0'
gem 'zmq'

